### ISSUE TITLE
실행 시 Cannot find module... 오류 발생

### ISSUE THREAD

**Issue by SkyLightQP** [leegeunhyeok/school-kr#15]
3.0.2로 업데이트 하니까 오류가 발생합니다.
TypeScript v3.4.5에서 사용했는데 혹시 몰라 JavaScript (Node.js v12.14.1)에서 다시 테스트하니까 동일한 오류가 발생합니다.

현재는 node-school-kr v2.2.2로 내리고 사용 중인데 이건 정상적으로 작동합니다.

추가로 `node_modules/school-kr` 에서 dist 폴더가 없었습니다.

- 테스트 코드
```
const School = require('school-kr');
const school = new School();
```

- 오류 내용
```
internal/modules/cjs/loader.js:305
      throw err;
      ^

Error: Cannot find module '프로젝트경로\node_modules\school-kr\dist\entry.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (프로젝트경로\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  path: '프로젝트경로\\node_modules\\school-kr\\package.json',
  requestPath: 'school-kr'
}
```

**Comment by minikupa** [comment]
저도 같은 오류가 발생하네요

**Comment by leegeunhyeok** [comment]
NPM 배포 중 미처 확인하지 못한 부분이 있었습니다.

확인 후 `3.0.3`으로 수정하여 재배포했습니다.


감사합니다 :)
